### ISSUE TITLE
Web page elements don't load across the width of the whole page when viewing via Safari

### ISSUE THREAD

**Issue by ArtursO** [Appleseed/leaves.lite#1]
1) This is how it looks on Safari **(incorrect)**:

![screen shot 2016-11-28 at 12 01 22 pm](https://cloud.githubusercontent.com/assets/6081495/20678276/19bd131e-b564-11e6-8ce5-9bbd5e6b7de4.png)

2) This is how it looks on Chrome **(correct)**:

![screen shot 2016-11-28 at 12 00 11 pm](https://cloud.githubusercontent.com/assets/6081495/20678299/3376ac0c-b564-11e6-87e3-abc9804c60a1.png)

**Comment by ArtursO** [comment]
This issue should've been addressed.

**Comment by mddanishyusuf** [comment]
@ArtursO after cloning go to the **leaves_ui** folder and build docker here

**Comment by ArtursO** [comment]
@mddanishyusuf what does this have to do with the safari issue reported?
