### ISSUE TITLE
Leaves - Big space between leaf list and reading area created when user hide tag area

### ISSUE THREAD

**Issue by SinghPrakash0206** [Appleseed/leaves.lite#100]
DEC:
When a user clicks on the hide tag button on the left, there is a vacant space created a big space is created between the leaf list and reading section.

AC: 
Reading section should expand and take up the gap generated.

Issue Video: https://www.screenmailer.com/v/sl7iNRlDqH3batA

**Comment by mddanishyusuf** [comment]
@SinghPrakash0206 ok. will fixed.

**Comment by mddanishyusuf** [comment]
@SinghPrakash0206 this is fixed in this commit https://github.com/Appleseed/leaves.lite/commit/4cb6e0a188d8bfc14b9fb0ae44846a064c8a46f7

**Comment by mddanishyusuf** [comment]
review the issue and close it.
