### ISSUE TITLE
Leaves - User can add same leaf multiple time in the reading section

### ISSUE THREAD

**Issue by SinghPrakash0206** [Appleseed/leaves.lite#102]
DEC:
When a user adds a particular leaf and adds another few leaves in the reading section and then close one tab, he is allowed to add the same leaf again.

AC: Once a particular leaf is added to the reading section, it should not be allowed to add again to avoid creating multiple copies. 

Issue Video: https://www.screenmailer.com/v/FbSQ3fS76bxJaFc

**Comment by mddanishyusuf** [comment]
It's fixed.
