### ISSUE TITLE
Leaves - Update the placeholder text in the Add New Leaf window

### ISSUE THREAD

**Issue by SinghPrakash0206** [Appleseed/leaves.lite#103]
DEC:
Currently, the input box placeholder of Add New Leaf window is "Enter URl" where the last character is small "L" instead of capital "L".

AC:
Update the input box placeholder to "Enter a URL"

Issue Screenshot:
![image](https://user-images.githubusercontent.com/40699379/44880638-0cc51e80-ac7b-11e8-8f4c-23761531f1c1.png)

**Comment by ArtursO** [comment]
FYI - I submitted a PR to fix this way back but I'm not sure it actually got merged. https://github.com/Appleseed/leaves.lite/pull/73

**Comment by mddanishyusuf** [comment]
It's fixed.
