### ISSUE TITLE
"Misspelled placeholder when adding a new leaf" 

### ISSUE THREAD

**Issue by akwio** [Appleseed/leaves.lite#107]
DES: When a user goes to add a new leaf the placeholder says "Please logged in" above "Site URL".

AC: The placeholder should read "Please log in". 

Screenshot: ![capture](https://user-images.githubusercontent.com/40698946/45374921-7f11f900-b5c1-11e8-86d4-637e74a99c1b.PNG)

**Comment by mddanishyusuf** [comment]
@akwio this issue fixed and already pushed to dev branch. I think code is not updated on production.
