### ISSUE TITLE
leaves - ui - reader pane doesn't show when clicking links from list view

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#25]
Desc: reader pane doesn't show when clicking links from list view

Steps to reproduce:

- open http://qrisp.eastus.cloudapp.azure.com:90/
- click on list view 
- click on first item 

Acceptance Criteria: When list item is clicked in this view, reader pane is shown.

**Comment by mddanishyusuf** [comment]
Yes. I'm working on it.

**Comment by mddanishyusuf** [comment]
Fixed.
