### ISSUE TITLE
leaves - ui - reader tab pane - tabs should get abbreviated 

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#28]
![image](https://user-images.githubusercontent.com/400761/30232923-82567906-94c0-11e7-8cb5-93e62c85394c.png)

​Desc: reader tab pane - tabs should get abbreviated 

Acceptance Criteria: Tabs should dynamically resize -- similar to this and should be close able. 

![image](https://user-images.githubusercontent.com/400761/30232970-ab4315fe-94c0-11e7-9d7f-0fc485623917.png)

**Comment by mddanishyusuf** [comment]
fixed and pushed.
