### ISSUE TITLE
leaves - ui - middle pane - gridview is wierd after switching back and forth from list

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#29]
![image](https://user-images.githubusercontent.com/400761/30233087-5b69200e-94c1-11e7-906a-309c1138a633.png)

​Desc:  middle pane - gridview is wierd after switching back and forth from list

Acceptance Criteria: Grid view should look like it normally does.. one on top of each other

**Comment by mddanishyusuf** [comment]
ok. I will check it and fixed the issue

**Comment by xingh** [comment]
verified this is fixed. .. it takes a second but it is okay
