### ISSUE TITLE
leaves - ui - reader pane - use something better for tab management?

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#30]
Desc: the tabs need to be robust.. no need to reinvent the wheel.. maybe use something like.. 

Acceptance Criteria: good robust tabs.

https://angular-ui.github.io/bootstrap/
http://nervgh.github.io/pages/angular-tabs/

**Comment by mddanishyusuf** [comment]
ok.

**Comment by xingh** [comment]
The tabs have a wierd issue now. To reproduce 

- in grid view, or list view, click on a leaf, it will open the reader 
- click on one or two more leaves
- then close one leafreader - it will replace it with a duplicate of another leafreader
- keep closing.. you'll see it keeps duplicating one leafreader 
- then when you close one of the many, all of the close.

**Comment by xingh** [comment]
https://github.com/rahil471/browser-like-tabs-angularjs

Check this one out.

**Comment by xingh** [comment]
Also this one. https://scotch.io/tutorials/build-chrome-like-tabs-with-bootstrap-and-angularjs

![image](https://user-images.githubusercontent.com/400761/30466105-6eafe6ba-99a9-11e7-9aa4-aacd1607eeda.png)

**Comment by mddanishyusuf** [comment]
Issues fixed.
