### ISSUE TITLE
leaves - ui - tags - tags w/ "." in them should carry through in the url

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#31]
Desc: 
When a tag has a space in it, it should have the space replaced with "-" but when its a period, it should not be replaced with "-"

Ac: if a tag is like "app.interfaces" , the tag link should be http://localhost:9000/#!/?tag=app.interfaces. Right now it shows "app-interfaces" and it doesnt show the links

**Comment by mddanishyusuf** [comment]
I checked this bug but I'm not splitting by "." and I'm splitting by "-" so that's not the case. Ans I also check that in the console. that's working fine.

**Comment by xingh** [comment]
I understand this.. but in another instance of wallabag I have tags such as "client.clientname" and it sets the tag as "client-clientname" in the URL. If I change it to "." in the URL , it works, otherwise there is no match

**Comment by mddanishyusuf** [comment]
Yes. i get the point and found a tag 'asp.net'. wallabag convert this tag into url-friendly and it's wallabag bugs. 

But I will fix this issue on my side.

**Comment by mddanishyusuf** [comment]
this issue fixed.
