### ISSUE TITLE
leaves - ui - refactor list-reader / card-reader / single-leaves into one component / directive

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#36]
​Desc: These files look identical but are called from different elements. It's confusing because of the multiple files. This doesn't follow the DRY (dont repeat yourself) principle. 

Acceptance Criteria: One leaves-reader that shows up when clicked from either list, card, or from a menu item if hidden ( another issue)

**Comment by mddanishyusuf** [comment]
Yes. I got it and will refactor the code.

**Comment by mddanishyusuf** [comment]
Fixed.

**Comment by xingh** [comment]
Verified.
