### ISSUE TITLE
leaves - ui - sidebar and listing are overlapping

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#37]
​Desc:  Sidebar search bar is overlapping toolbar in Listing 

Acceptance Criteria: The sidebar should  be as wide as the search bar. 

![image](https://user-images.githubusercontent.com/400761/32692154-f4cf924a-c6e0-11e7-8af9-c9cfd0ce46e6.png)

**Comment by xingh** [comment]
Need to change col-md-2 / col-md-10 split to col-md-3 / col-md-9 

![image](https://user-images.githubusercontent.com/400761/32692173-48049550-c6e1-11e7-997d-2644430ea7c4.png)

**Comment by mddanishyusuf** [comment]
That's not the change need for that. I fixed this issues. And Pushing it.
