### ISSUE TITLE
leaves - ui - add a "virtual tag" for "Inbox" which when clicked shows reader view (instead of toggle)

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#38]
​Desc: There should be a way to toggle to the reader view. 

Acceptance Criteria: If there is at least one selected article, the "Inbox" virtual tag should appear. This way when the user browses off the reader by selecting a tag, they can go back to see what they have selected. It should also show how many items are in there.

**Comment by xingh** [comment]
Use the folder glyphicon with the bootstrap badge span class
![image](https://user-images.githubusercontent.com/400761/32692255-804d4294-c6e2-11e7-866c-0df650ee23b0.png)

![image](https://user-images.githubusercontent.com/400761/32692260-97a25e3e-c6e2-11e7-93b3-ea52760cbe42.png)

**Comment by xingh** [comment]
changed my mind about this one.. i think a "virtual tag" that remains at the top of tag list under the search bar and is colored differently would be better.. maybe there can be a divider between the inbox tag and the other tags..

**Comment by xingh** [comment]
i see it but clicking on it doesn't take me to the reader @mddanishyusuf

**Comment by mddanishyusuf** [comment]
@xingh now it's fixed

**Comment by xingh** [comment]
verified
