### ISSUE TITLE
leaves - ui - list / card list view have different color backgrounds

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#39]
​Desc: The issue is more that the tool bar should be separate from the listing or the card view. 

Acceptance Criteria: Toolbar should be above both card / list view with the normal gray background as it is in the card list view. 

Card list View 
![image](https://user-images.githubusercontent.com/400761/32692284-23bf6894-c6e3-11e7-808d-cf5528ad453d.png)

List list View 
![image](https://user-images.githubusercontent.com/400761/32692287-30447d3e-c6e3-11e7-94fa-e14e8bc38158.png)

**Comment by mddanishyusuf** [comment]
fixed. commit locally and will push when other will resolved.

**Comment by xingh** [comment]
Verified
