### ISSUE TITLE
leaves - ui - in the leaves reader have a way to read the original in an iframe

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#40]
​Desc: Needs to be flushed out, but I was thinking that under the title, it has the user, a button for the original link ( these are in place now ), a link to the reader view, and a link to the iframe view. 

Acceptance Criteria: User should be able to see the contents of the original link in an iframe that fits int the place of the reader content when clicked. If they click on reader, it goes  back to default view. This could be a tabbed interface toggling between reader / original view.

**Comment by mddanishyusuf** [comment]
Done. But there are some URLs that we can't frame on the web.

**Comment by xingh** [comment]
Ok. This is fine for now. Verified.
