### ISSUE TITLE
leaves - ui - tag navigation similar to medium / should be collapsible with button  before categories text

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#46]
​Desc:   tag / category navigation should be like medium in that when you click it shows a grid, and there is a option to pin the list to the left side as it is now. if hamburger button is clicked it is hidden. 

Acceptance Criteria: 1. Need to have a category / tag view similar to Medium when clicking on "Categories"

![img_20171219_165009](https://user-images.githubusercontent.com/400761/34258842-d681f14a-e62d-11e7-8047-791a830e5f84.jpg)

2. Need to have "hamburger menu" Similar to 

![image](https://user-images.githubusercontent.com/400761/33080725-c673d3ca-cea6-11e7-8e00-a357d186ef8e.png)

Toggle the left menu. 

![image](https://user-images.githubusercontent.com/400761/33080696-b411ac8e-cea6-11e7-9d3b-aac486d8ea95.png)

**Comment by mddanishyusuf** [comment]
Yes. this is implemented and push to the codebase(dev branch).
