### ISSUE TITLE
leaves - topic.app - clean up / make a clean ui like anant.co

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#47]
​Desc: Need to have a "landing" home page. ​This would look something like anant.co or anant.co/topic.html until someone clicks on a link, which then will go into the reader view. This will probably be a different docker container or maybe the same which does a simple read only and uses the existing anant.co template but populates from API not from the json. 

Acceptance Criteria: User can go to a / and it shows a page like anant.co 

![image](https://user-images.githubusercontent.com/400761/33081358-29bc53b6-cea8-11e7-8722-c9f035c04cc9.png)

or 

the Docker prototype

![image](https://user-images.githubusercontent.com/400761/33081384-41e3a458-cea8-11e7-8a00-738cba6eb0ca.png)

**Comment by mddanishyusuf** [comment]
Yes. that's good. to make landing page first I will make a wireframe (mean do some UX part) and will share you the design of landing page. I think that will be good. just let me know your view on it.

**Comment by xingh** [comment]
Done, except, the embedly not currenrtly being used because there is an API limit
