### ISSUE TITLE
leaves - api  - error throwing when make POST request for adding URL

### ISSUE THREAD

**Issue by mddanishyusuf** [Appleseed/leaves.lite#48]
Desc: When submitting URL through wallabag API giving error "500 internal errors". I think there are some writing issues on server or API is not granted for adding URLs.
![500-internal-server-error](https://user-images.githubusercontent.com/9165019/33083003-37144508-cf04-11e7-8323-010b6fb28c04.png)

**Comment by xingh** [comment]
when i added http://www.anant.us I didn't get an error - but it knew i was logged in.. or it was using my token, but it seems to not have gotten the contents of the payload. 



`{"is_archived":0,"is_starred":0,"user_name":"admin","user_email":"rahul.singh@anant.us","user_id":1,"tags":[],"is_public":false,"id":8881,"uid":null,"title":null,"url":null,"content":null,"created_at":"2017-12-24T09:44:07+0000","updated_at":"2017-12-24T09:44:07+0000","published_at":null,"published_by":null,"starred_at":null,"annotations":null,"mimetype":null,"language":null,"reading_time":0,"domain_name":null,"preview_picture":null,"http_status":null,"headers":null,"origin_url":null,"_links":{"self":{"href":"\/api\/entries\/8881"}}}`
