### ISSUE TITLE
leaves - ui - url is being encoded, braking shareability

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#49]
![image](https://user-images.githubusercontent.com/400761/33719807-fa308c40-db2f-11e7-991f-fce59890b4d2.png)

​Desc: Users should be able to share the URL after picking items and have the other user see the same listing. Right now , for some reason this feature stopped working. 

Acceptance Criteria: URL shouldnt be like this: 

http://qrisp.eastus.cloudapp.azure.com:90/#!/leaf/2703%252C2719%252C4605%252C2702%252C4911?tag=cassandra

but rather 

http://qrisp.eastus.cloudapp.azure.com:90/#!/leaf/2703,2719,4605,2702,4911?tag=cassandra

**Comment by mddanishyusuf** [comment]
leaves - ui - url is being encoded, braking shareability - FIxed

**Comment by xingh** [comment]
Let's not encode the link. 

This is the desired format http://qrisp.eastus.cloudapp.azure.com:90/#!/leaf/8861%252C8857%252C8852%252C8850%252C8849%252C8860%252C8846%252C6681?tag=admin
