### ISSUE TITLE
leaves - ui - integrate leaves.topic into leaves.app

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#64]
​Desc: The leaves.topic layout can be integrated into the leaves.app . Right now it's literally a CSS, HTML, and a JS file. 

Acceptance Criteria:

1. Component is separate so that it can still be used in leaves.topic 
2. Component is included in leaves.home
3. Component is easily / are easily embedded into other systems 
4. The icon will be next to the list and grid view . 
![image](https://user-images.githubusercontent.com/400761/34323585-1dbfffa6-e81e-11e7-8d20-25219a11fd78.png)

**Comment by mddanishyusuf** [comment]
@xingh is this issues still valid?

**Comment by xingh** [comment]
No can be closed

Rahul Singh

Chief Executive Officer | Internet Architecture

m 202.905.2818 | View my profile <http://linkedin.com/in/xingh> | Team
Office Hours <http://links.anant.us/rs.office.hours> | Appointment Calendar
<https://calendly.com/xingh/>

1010 Wisconsin Ave NW, Suite 250

Washington, D.C. 20007

To empower people through the Internet to create a better world.

How are we doing? Please take our survey.
<https://anantcorp.wufoo.com/forms/zqo0ylp0h8igra/>

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of Anant Corporation. If you are not the intended recipient
of this email, you must neither take any action based upon its contents,
nor copy or show it to anyone. Please contact the sender if you believe you
have received this email in error.
