### ISSUE TITLE
leaves - ui - embedded content doesn't show up well - youtube

### ISSUE THREAD

**Issue by ArtursO** [Appleseed/leaves.lite#72]
Video of issue: https://www.screenmailer.com/v/Vo4yyuuo0aocoAc
Outgoing link to youtube just send me to an XML file

_For Startup Lab workshop: How Google sets goals: OKRs_ - the link found in leaves is 

`http://www.youtube.com/oembed?format=xml&url=https://www.youtube.com/watch?v=mJB83EZtAjc`

**Comment by mddanishyusuf** [comment]
Yes, Arthur. But someone add that xml link. So, when you click on 'link' it will open added leaf link.

**Comment by xingh** [comment]
@mddanishyusuf that is how Wallabag saves it when it is something like youtube. It then processes it a special way to embed the content. The xml then has the link to Iframe. 



![image](https://user-images.githubusercontent.com/400761/34727683-ae4e17ce-f525-11e7-9b5d-453719833b6d.png)

**Comment by xingh** [comment]
We may need to use an ombed library in angular/js to handle this. 

https://github.com/ritz078/ng-embed

**Comment by mddanishyusuf** [comment]
@xingh I will use this ng-embed

**Comment by mddanishyusuf** [comment]
Will use ng-embed. I'm trying to figure out how many case will be there. what if use add wrong URL like some add this URL: "ttps://www.youtube.com/watch?v=98ya1LiEU00" without 'h'. so for that I have to make some basic validation while adding leaf.

**Comment by xingh** [comment]
I dont think the system will parse bad links Wallabag cleans it before it
hits DB

Rahul Singh

Chief Executive Officer | Internet Architecture

m 202.905.2818 | View my profile <http://linkedin.com/in/xingh> | Team
Office Hours <http://links.anant.us/rs.office.hours> | Appointment Calendar
<https://calendly.com/xingh/>

1010 Wisconsin Ave NW, Suite 250

Washington, D.C. 20007

To empower people through the Internet to create a better world.

How are we doing? Please take our survey.
<https://anantcorp.wufoo.com/forms/zqo0ylp0h8igra/>

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of Anant Corporation. If you are not the intended recipient
of this email, you must neither take any action based upon its contents,
nor copy or show it to anyone. Please contact the sender if you believe you
have received this email in error.

**Comment by SinghPrakash0206** [comment]
The issue has been tested and found working as per expectation.
Issue re-test vedio: screenmailer.com/v/pUxa2aa34cFgMAA
