### ISSUE TITLE
leaves - backend - wallabag is experiencing formatting issues on Chrome (Version 63.0.3239.132 (Official Build) (64-bit))

### ISSUE THREAD

**Issue by ArtursO** [Appleseed/leaves.lite#75]
Currently seeing this when looking at wallabag:

![image](https://user-images.githubusercontent.com/6081495/35171282-42a3543a-fd31-11e7-8ecf-71d788a46b00.png)
![image](https://user-images.githubusercontent.com/6081495/35171295-4f97239c-fd31-11e7-8972-a83878bb89eb.png)

These are the errors appearing in the console:
[qrisp.eastus.cloudapp.azure.com-1516395497639.txt](https://github.com/Appleseed/leaves.lite/files/1647896/qrisp.eastus.cloudapp.azure.com-1516395497639.txt)

@mddanishyusuf could you look at this and propose a solution?

**Comment by ArtursO** [comment]
@mddanishyusuf could you look into this?

**Comment by mddanishyusuf** [comment]
@ArtursO  there is CORS issues and I don't have server access. Origin 'http://qrisp.eastus.cloudapp.azure.com' is therefore not allowed access external resources.

![cors-error](https://user-images.githubusercontent.com/9165019/35482271-a1a42562-0458-11e8-835c-a9082d25d7a0.png)

**Comment by ArtursO** [comment]
@xingh could you @mddanishyusuf server access so he can fix this?

This issue is occurring for both me and Tom - I cleared cache & cookies and the problem still shows.

**Comment by ArtursO** [comment]
This issue happens to me when I go to http://qrisp.eastus.cloudapp.azure.com/ but not when I go to leaves.anant.us

![qrisp](https://user-images.githubusercontent.com/6081495/35632636-2db45a22-0675-11e8-810c-3400edddefba.png)

![leaves anant us](https://user-images.githubusercontent.com/6081495/35632637-2dbf4798-0675-11e8-83a5-f0f70385322f.png)

**Comment by xingh** [comment]
We moved the domain to leaves.anant.us and so that means you have to go to the new domain.
