### ISSUE TITLE
leaves - frontend - adding link displays errors

### ISSUE THREAD

**Issue by ArtursO** [Appleseed/leaves.lite#76]
This occurred when I tried to add this link https://neilpatel.com/what-is-content-marketing/ to leaves.anant.us

You can see the error log at this link - https://anantco.slack.com/files/U39GKV81M/F9595BR71/error_from_the_55__internal_server_page.txt

![image](https://user-images.githubusercontent.com/6081495/35831715-b8379a7a-0a98-11e8-901a-483f6976ab0f.png)

![image](https://user-images.githubusercontent.com/6081495/35831726-bd8aee00-0a98-11e8-8bfc-e9305f296cfb.png)

**Comment by xingh** [comment]
Related to Wallabag. Will have to update to latest version and see if it goes away or submit an issue in Wallabag and see if someone fix it in their core. Or we will fix it and submit a patch.

**Comment by xingh** [comment]
I found the resolution to it. It has to do with configuring MariaDB / MYSQL 

https://github.com/wallabag/docker/issues/105

Please add `SYMFONY__ENV__DATABASE_CHARSET` and `db` `command` to the example.

**Comment by xingh** [comment]
The neilpatel article makes it but the medium article doesnt. Still working on it.

**Comment by xingh** [comment]
was able to leaf https://medium.com/deep-learning-turkey/google-colab-free-gpu-tutorial-e113627b9f5d which was previously causing issues.
