### ISSUE TITLE
Use Bit.ly to Share Leaves URL

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#78]
Desc: user is able to share colleciton of leaves and the link that is copied is a bit.ly link. 
AC: User is able to click "share" and see the link as a bit.ly link and copy it . 

![image.png](https://images.zenhubusercontent.com/5ab03c424b5806bc2bcb857c/30cb3906-67de-470a-9481-0c2845b4e6be)

**Comment by mddanishyusuf** [comment]
Done.
