### ISSUE TITLE
leaves - ui - the column width on the card view is 12 when no tag or leaf is chosen 

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#79]
Desc: the column width on the card view is 12 when no tag or leaf is chosen 

Broken:
![image](https://user-images.githubusercontent.com/400761/37768227-d6238eca-2d9a-11e8-8626-d014570a4c5d.png)

AC: When no tag or leaf is chosen, it should look normal. 

Normal:
![image](https://user-images.githubusercontent.com/400761/37768217-cb97ed5c-2d9a-11e8-83a8-b805abfb8664.png)

**Comment by mddanishyusuf** [comment]
Fixed.
