### ISSUE TITLE
several ui issues - sidebar width, share link - reader layout

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#82]
Current build 
![image](https://user-images.githubusercontent.com/400761/38449951-c17b2d5c-39e3-11e8-9d14-9036c0ca25a4.png)

New build 
![image](https://user-images.githubusercontent.com/400761/38449928-7e16a794-39e3-11e8-8bf2-32b85d756c8d.png)

**Comment by xingh** [comment]
1. the middle card pane shouldnt over lap - see first image 
2. The "Share thread" doesn't work. Lets call it "Share branch". 
At the very least - it should put into the clipboard a link like this http://localhost:9000/#!/leaf/115,119,120,128,1659,7118,120?tag=business&branch=branchname

**Comment by xingh** [comment]
also the share branch button should be to the left of the inbox button as a popup like in github.com - except instead of a green button it should be text with an icon "share "

![image](https://user-images.githubusercontent.com/400761/38450022-9586a068-39e4-11e8-93a6-cf1a240a6f40.png)

**Comment by mddanishyusuf** [comment]
Ok. Rahul

**Comment by mddanishyusuf** [comment]
Hey Rahul,

1. the middle card pane shouldnt over lap - no issue on my build.
![image](https://user-images.githubusercontent.com/9165019/38772335-a3814038-4051-11e8-958a-f5798b053e9c.png)
2. The "Share thread" doesn't work. Lets call it "Share branch". I'm keeping bitly shortern link. what the mean this params "&branch=branchname".
3. share modal design set like github.

I'm going to push changes to 'dev' branch

**Comment by mddanishyusuf** [comment]
Please review the change and close this issue.

Thanks.

**Comment by mddanishyusuf** [comment]
Hey Rahul,

The overlap issues is fixed.
