### ISSUE TITLE
leaves - devops - use environment variables in composition for base_url and token

### ISSUE THREAD

**Issue by xingh** [Appleseed/leaves.lite#91]
`    $scope.base_url = 'http://leaves.anant.us:82'
    $scope.card_view = true
    $rootScope.readerFromInbox = true
    $rootScope.listArray = []
    $rootScope.tempArray = []
    $rootScope.leaves = []
    $scope.token = 'N2Y1YmFlNzY4OTM3ZjE2OGMwODExODQ1ZDhiYmQ5OWYzMjhkZjhiMDgzZWU2Y2YyYzNkYzA5MDQ2NWRhNDIxYw'
`

currently, anywhere its using http://leaves.anant.us:82 should be an environment variable 
same with the token above. 

It's in this code base here.. 

https://github.com/Appleseed/leaves.lite/blob/master/leaves.app/client/js/controllers.js

**Comment by mddanishyusuf** [comment]
done.
