### ISSUE TITLE
The link URL of a leaf with YouTube content is incorrect

### ISSUE THREAD

**Issue by SinghPrakash0206** [Appleseed/leaves.lite#98]
DES: 
When a user clicks on the 'link' attribute of a leaf which has YouTube content, the embedded content does not open up in the new tab. 
Issue Video: screenmailer.com/v/I7CbMMaidlcaAnk
Environment: Dev,Stage,Prod

AC:
A user should be able to open the youtube page after clicking the 'link' feature both in page list and Read section.

**Comment by mddanishyusuf** [comment]
@SinghPrakash0206 will look into this.

**Comment by mddanishyusuf** [comment]
This is fixed. https://github.com/Appleseed/leaves.lite/commit/017ae9ec5048ab0ec594fb0269b4d4f68d5bef7c
